{
  'branches': ['main'],
  'plugins':
    [
      '@semantic-release/commit-analyzer',
      '@semantic-release/release-notes-generator',
      '@semantic-release/changelog',
      ['@semantic-release/npm', { 'npmPublish': false }],
      ['@semantic-release/exec', { 'prepareCmd': '.github/scripts/publish.sh ${nextRelease.version}' }],      
      [
        '@semantic-release/github',
        {
          'assets':
            [
              { 'path': 'releases/*.zip', 'label': 'Plugin zip file' },
              { 'path': 'releases/*.md5', 'label': 'Plugin zip file checksum' }
            ]
        }
      ],
      [
        '@semantic-release/git',
        {
          'message': "chore(release): <%= nextRelease.version %> - <%= new Date().toLocaleDateString('en-US', {year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }) %> [skip ci]\n\n<%= nextRelease.notes %>"
        }
      ]
    ],
}