{
 "title": "Data Transferred",
 "tags": [
  "Azion",
  "Edge Applications",
  "Data Transferred "
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Missed Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedBandwidthMissedlData {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts,\n    bandwidthMissedData\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Edge Caching",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedDataTransferred {\n  httpMetrics(\n    limit: 2000\n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    }\n    groupBy:[ts]\n    orderBy:[ts_ASC]\n  )\n  {\n    ts\n    dataTransferredIn\n    dataTransferredOut\n    dataTransferredTotal\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Saved Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedBandwidthSavedlData {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts,\n    bandwidthSavedData\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Saved Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedSavedData { \n  httpMetrics( \n    limit: 1000,\n    filter: { \n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" }, \n    },\n    groupBy: [ts] \n    orderBy: [ts_ASC]\n  )\n   { \n     ts\n     savedData\n   } \n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Bandwidth Offloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedBandwidthOffload {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts,\n    bandwidthOffload\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Missed Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedMissedData {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts,\n    missedData\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Total Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedBandwidthTotalData {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts,\n    bandwidthTotal\n  }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Edge Offload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataPath": "httpMetrics",
     "dataSourceSelect": { "label": "Metrics", "value": "metrics" },
     "endTimePath": "endTime",
     "optionsDataSource": [
      { "label": "Metrics", "value": "metrics" },
      { "label": "Events", "value": "events" }
     ],
     "queryText": "query HttpCalculatedEdgeOffload {\n  httpMetrics(\n    limit: 1000, \n    filter: {\n      tsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n    },\n    groupBy: [ts]\n    orderBy: [ts_ASC]\n          ) \n  {        \n    ts\n    offload\n  }\n}",
     "timePath": "Time"
    }
   ]
  }
 ]
}