{
 "title": "Http Metrics Examples",
 "tags": [
  "azion",
  "HttpMetrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "base_url",
    "query": "https://stage-beholder.azion.com/metrics/graphql"
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query aggBytesSent {\n\thttpMetrics(\n\t\taggregate: { avg: requestTime }\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\t\t\trequestTimeGt: 0 \n\t\t}\n\t) {\n\t\tavg\n\t}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query httpBytesSentAverage {\n\thttpMetrics(\n\t\taggregate: { avg: bytesSent }\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\t\t\tbytesSentGt: 0 \n\t\t}\n\t) {\n\t\tavg\n\t}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "options": {
    "content": "##Debug Grafana Variables\n|Variable|Value|\n---------|------\n|**__from:**|`${__from:date:iso}`|  \n|**__to:**|`${__to:date:iso}`|\n|**base_url:**|`${base_url}`|"
   },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query {\n      data:submissions(user:\"$user\"){\n          Time:submitTime\n          idle running completed\n      }\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Request Time Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query aggBytesSent {\n\thttpMetrics(\n\t\tlimit: 2000\n\t\taggregate: { count: requestTime }\n\t\tgroupBy: [requestTime]\n\t\torderBy: [requestTime]\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\t\t\trequestTimeGt: 0 \n\t\t}\n\t) {\n\t\trequestTime\n\t\tcount\n\t}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Requests per minute/hour/day",
   "type": "timeseries",
   "description": "Each query interval is used according to the following definitions:\nMinute: used for queries in the interval of up to 3 days.\nHour: used for queries in the interval of 3 and 60 days.\nDay: used for queries in the interval of over 60 days.",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query aggRequests {\n\thttpMetrics(\n\t\tlimit: 2000\n    aggregate: {sum:requests}\n\t\tgroupBy: [ts]\n\t\torderBy: [ts_ASC]\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" }\n\t\t}\n\t) {\n\t\tts\n\t\tsum\n\t}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Average Request Time per minute/hour/day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query aggBytesSent {\n\thttpMetrics(\n\t\tlimit: 2000\n\t\taggregate: { avg: requestTime }\n\t\tgroupBy: [ts]\n\t\torderBy: [ts_ASC]\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" },\n\t\t\trequestTimeGt: 0 \n\t\t}\n\t) {\n\t\tts\n\t\tavg\n\t}\n}",
     "timePath": "Time"
    }
   ]
  },
  {
   "title": "Minute/Hour/Day Aggregated Events",
   "type": "table",
   "description": "Each query interval is used according to the following definitions:\nMinute: used for queries in the interval of up to 3 days.\nHour: used for queries in the interval of 3 and 60 days.\nDay: used for queries in the interval of over 60 days.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "httpMetrics",
     "endTimePath": "endTime",
     "queryText": "query httpRequestCount {\n\thttpMetrics(\n\t\tlimit: 2000\n\t\torderBy: [ts_DESC]\n\t\tfilter: {\n\t\t\ttsRange: { begin: \"${__from:date:iso}\", end: \"${__to:date:iso}\" }\n\t\t}\n\t) {\n\t\tts\n\t\thost\n\t\trequestMethod\n\t\tupstreamCacheStatus\n\t\tstatus\n\t\tscheme\n\t\tgeolocCountryName\n\t\tgeolocRegionName\n\t\tbytesSent\n\t\trequests\n\t}\n}\n",
     "timePath": "Time"
    }
   ]
  }
 ]
}