name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Check types
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      # - name: Unit tests 
      #   run: yarn test:ci
      - name: Build frontend
        run: yarn build

      - name: Start grafana docker
        run: yarn server -d

      - name: Run e2e tests
        run: yarn e2e

      - name: Stop grafana docker
        run: docker-compose down
  generate-tags:
    needs: build
    name: generate-tags
    runs-on: self-hosted
    container:
      image: node:16-alpine3.12
    permissions: 
      contents: write
      packages: write
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --immutable --prefer-offline

    - name: Build application
      run: yarn build
      
    - name: Release to NPM modules
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn semantic-release