name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn ci

      - name: Check types
        run: yarn typecheck

      - name: Build frontend
        run: yarn build

      - name: Start grafana docker
        run: yarn server -d

      - name: Run e2e tests
        run: yarn e2e

      - name: Stop grafana docker
        run: docker-compose down