name: Deploy to Stage

on:
  push:
    branches:
      - dev

env:
  HUSKY: 0

jobs:
  deploy-package:
    if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Install SO deps
        run: apk add curl git bash

      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install dependencies
        run: yarn ci

      - name: Build application
        run: yarn build
        
      - name: Setup AWS credentials
        if: ${{ secrets.S3_AZTECHJS_ID != '' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_AZTECHJS_ID }}
          aws-secret-access-key: ${{ secrets.S3_AZTECHJS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3 (Stage)
        if: ${{ secrets.S3_AZTECHJS_ID != '' }}
        run: |
          aws s3 cp --recursive --exclude "*" --include "*"  dist/  s3://aztechjs/grafana-plugin
      