name: Deploy to Stage

on:
  pull_request:
    types: [closed]
    branches:
      - dev
  push:
    branches:
      - dev

env:
  HUSKY: 0

jobs:
  deploy-package:
    if: ${{ github.event.pull_request.merged || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Install SO deps
        run: apk add curl git bash

      - name: "Checkout"
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'

      - name: Install dependencies
        run: yarn ci

      - name: Build application
        run: yarn build
      