name: Run Unit Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev
env:
    HUSKY: 0

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SO deps
      run: apk add curl bash

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn install --immutable --prefer-offline
    
    - name: Run unit tests 
      run: yarn test:ci

    - uses: actions/upload-artifact@v2
      with:
        name: coverage_unit_report
        path: coverage/lcov.info
        retention-days: 1
  sonarqube:
    needs: run-tests
    name: SonarQube
    runs-on: [self-hosted, sonarqube]
    timeout-minutes: 5
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage_unit_report
      - name: fix code coverage paths - lcov.info
        run: sed -i 's:/__w/grafana-plugin/grafana-plugin/:/github/workspace/:' lcov.info
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  