name: Run Unit Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev
env:
    HUSKY: 0

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SO deps
      run: apk add curl bash

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn ci
    
    - name: Run unit tests 
      run: yarn test:ci
