name: Run E2E Tests

on:
  push:
    branches:
      - dev
env:
    HUSKY: 0

jobs:
  run-tests-e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable --prefer-offline
    
    - name: Check types
      run: yarn typecheck

    - name: Build frontend
      run: yarn build

    - name: Start grafana docker
      run: yarn server -d

    - name: Run e2e tests
      run: yarn e2e

    - name: Stop grafana docker
      run: docker-compose down