name: Run E2E Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - dev
env:
    HUSKY: 0

jobs:
  run-tests:
    if: false
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine3.16

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SO deps
      run: apk add curl bash
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn ci

    - name: Check types
      run: yarn typecheck

    - name: Build frontend
      run: yarn build

    - name: Start grafana docker
      run: yarn server -d

    - name: Run e2e tests
      run: yarn e2e

    - name: Stop grafana docker
      run: docker-compose down