name: Run Unit Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
env:
    HUSKY: 0

jobs:
  run-tests:
    runs-on: self-hosted
    container:
      image: node:16-alpine3.16

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SO deps
      run: apk add curl bash

    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: "@aziontech"
        always-auth: true
      env:
          NODE_AUTH_TOKEN:  ${{ secrets.GH_PACKAGES_SECRET }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn ci
    
    # - name: Run unit tests 
    #   run: yarn test:ci

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage_unit_report
    #     path: coverage/lcov.info
    #     retention-days: 1